version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 22
  pre_build:
    commands:
      - echo Build started on `date`
  build:
    commands:
      - echo Building Task Management Backend...
      - cd backend
      - mvn clean package -DskipTests
      - echo Verifying JAR file...
      - ls -la target/
      - file target/task-management-backend.jar
      - cp target/task-management-backend.jar application.jar
      - echo Backend JAR created with Excel upload fix
      - echo JAR size: $(stat -c%s application.jar) bytes
      - cd ../frontend/hello-frontend
      - echo Building Task Management Frontend...
      - npm install
      - npm run build
      - echo Frontend build complete
artifacts:
  files:
    - backend/application.jar
    - backend/Procfile
    - backend/.ebextensions/**/*
    - frontend/hello-frontend/dist/**/*
    - Dockerfile