name: Deploy to AWS
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
    - uses: actions/setup-node@v3
      with:
        node-version: '22'
    
    - name: Build Backend
      run: |
        cd backend
        mvn clean package -DskipTests
    
    - name: Build Frontend
      run: |
        cd frontend/hello-frontend
        npm install
        npm run build
    
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: hello-backend
        environment_name: hello-backend-env
        version_label: ${{ github.sha }}
        region: us-east-1
        deployment_package: backend/target/hello-backend-1.0.0.jar